force-app/main/default/objects/Authorisation_Pin__c/Authorisation_Pin__c.object-meta.xml
<CustomObject>
    <label>Authorisation Pin</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Authorisation Pins Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Pin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Authorisation_Pin__c/fields/Attempts__c.field-meta.xml
<CustomField>
    <fullName>Attempts__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Attempts</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Authorisation_Pin__c/fields/PIN__c.field-meta.xml
<CustomField>
    <fullName>PIN__c</fullName>
    <label>PIN</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PasswordManagerService.cls
public with sharing class PasswordManagerService {
    public PasswordManagerService() {

    }

    public static List<Authorisation_Pin__c> getAuthPin(){
        String userId = UserInfo.getUserId();
        return [select PIN__c,Attempts__c,CreatedBy.FirstName,CreatedBy.LastName,CreatedBy.Email from Authorisation_Pin__c where CreatedById = :userId];
    }

    public static void sendEmail(String[] toAddresses,String senderName,String subject,String body){
        // Messaging.reserveSingleEmailCapacity(2);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        // Assign the addresses for the To and CC lists to the mail object.
        mail.setToAddresses(toAddresses);

        // Specify the name used as the display name.
        mail.setSenderDisplayName(senderName);

        // Specify the subject line for your email address.
        mail.setSubject(subject);

        // Optionally append the salesforce.com email signature to the email.
        // The email address of the user executing the Apex Code will be used.
        mail.setUseSignature(false);

        mail.setHtmlBody(body);

        // Send the email you have created.
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}