force-app/main/default/objects/Aadhar__c/Aadhar__c.object-meta.xml
<CustomObject>
    <label>Aadhar</label>
    <nameField>
        <displayFormat>Enroll-{0000}</displayFormat>
        <label>Aadhar Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aadhar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/Insurance__c.object-meta.xml
<CustomObject>
    <label>Insurance</label>
    <nameField>
        <label>Insurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance__c/fields/Aadhar__c.field-meta.xml
<CustomField>
    <fullName>Aadhar__c</fullName>
    <label>Aadhar</label>
    <referenceTo>Aadhar__c</referenceTo>
    <relationshipLabel>Insurances</relationshipLabel>
    <relationshipName>Insurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Cover_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cover_Amount__c</fullName>
    <label>Cover Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <formula>ADDMONTHS(Issued_On__c , Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/insuranceExtension.cls
public class insuranceExtension {
    public List<Insurance__c> listInsurance{get;set;}
    
    public void runMeFirst(){
        listInsurance = [select Aadhar__c,Cover_Amount__c,Duration__c,Premium__c,Maturity_Date__c from Insurance__c];

         for(Insurance__c obj : listInsurance )
        {
            obj.Cover_Amount__c = 123456;
        }
        if(listInsurance.size() > 0)
        {
            update listInsurance;//this seems to just update the list. How do I actually update the custom object?
        }
    }
    
}