force-app/main/default/objects/Aadhar__c/Aadhar__c.object-meta.xml
<CustomObject>
    <label>Aadhar</label>
    <nameField>
        <displayFormat>Enroll-{0000}</displayFormat>
        <label>Aadhar Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aadhar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aadhar__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <description>Captures Aadhar Number</description>
    <inlineHelpText>Captures Aadhar Number</inlineHelpText>
    <label>Aadhar Number</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Aadhar__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of a aadhar holder</description>
    <inlineHelpText>Name of a aadhar holder</inlineHelpText>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MyTestClass.cls
@Istest
public class MyTestClass {
    static testMethod void validateDateOfBirth(){
        Aadhar__c a = new Aadhar__c(Name__c = 'Rakesh',
                                   Phone_Number__c = '24',
                                   Date_Of_Birth__c = Date.newInstance(2019, 2, 11),
                                   Aadhar_Number__c = 215611651);
        
        insert a;
        
        Aadhar__c j = [select id,name from Aadhar__c where id = :a.Id];
        system.assertEquals(Date.today(), j.Date_Of_Birth__c);
        
        
    }
}