force-app/main/default/objects/Co_Scholastic__c/Co_Scholastic__c.object-meta.xml
<CustomObject>
    <label>Co Scholastic</label>
    <nameField>
        <label>Co Scholastic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co Scholastics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Scholastic__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Students</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marksheet__c/Marksheet__c.object-meta.xml
<CustomObject>
    <label>Marksheet</label>
    <nameField>
        <label>Marksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marksheet__c/fields/Half_Yealry_80__c.field-meta.xml
<CustomField>
    <fullName>Half_Yealry_80__c</fullName>
    <label>Half Yealry (80)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marksheet__c/fields/Marks_Obt_100__c.field-meta.xml
<CustomField>
    <fullName>Marks_Obt_100__c</fullName>
    <label>Marks Obt. (100)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marksheet__c/fields/Notebook__c.field-meta.xml
<CustomField>
    <fullName>Notebook__c</fullName>
    <label>Notebook</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marksheet__c/fields/PT1__c.field-meta.xml
<CustomField>
    <fullName>PT1__c</fullName>
    <label>PT1</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marksheet__c/fields/Sub_Enrichment_5__c.field-meta.xml
<CustomField>
    <fullName>Sub_Enrichment_5__c</fullName>
    <label>Sub. Enrichment (5)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Marksheet__c/fields/Subjects__c.field-meta.xml
<CustomField>
    <fullName>Subjects__c</fullName>
    <label>Subjects</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Sanskrit</fullName>
            </value>
            <value>
                <fullName>Maths</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>SO. Science</fullName>
            </value>
            <value>
                <fullName>Computer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>All Students registered in library</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MarksheetController.cls
public with sharing class MarksheetController {
    public MarksheetController() {

    }

    @AuraEnabled
    public static void saveMarksheet(List<Marksheet__c> records){
        System.debug(records);
        upsert records;
    }
    
    @AuraEnabled
    public static void saveCoScholastic(List<Co_Scholastic__c> records){
        System.debug(records);
        upsert records;
    }
    
    @AuraEnabled
    public static void deleteMarksheet(List<Marksheet__c> records,List<Id> deleteRecords){
       upsert records;
        delete [select id from Marksheet__c where id in :deleteRecords];
    }
    
    @AuraEnabled
    public static  Map<String,List<Marksheet__c>> getAllMarksheets(){
        // return [SELECT Student__c,Subjects__c,PT1__c,Notebook__c,Sub_Enrichment_5__c,Half_Yealry_80__c,Marks_Obt_100__c,Grade__c FROM Marksheet__c];
        List<Marksheet__c> marksheetList = [SELECT Student__c,Subjects__c,PT1__c,Notebook__c,Sub_Enrichment_5__c,Half_Yealry_80__c,Marks_Obt_100__c,Grade__c FROM Marksheet__c ORDER BY Student__c ASC NULLS FIRST];
        Map<String,List<Marksheet__c>> mapMarksheet = new Map<String,List<Marksheet__c>>();
        for(Marksheet__c marksheet : marksheetList){
            List<Marksheet__c> ls ;
            if(mapMarksheet.get(marksheet.Student__c) != null){
                ls = mapMarksheet.get(marksheet.Student__c);
            }else{
                ls = new List<Marksheet__c>();
            }
            ls.add(marksheet);
            mapMarksheet.put(marksheet.Student__c,ls);
        }
        return mapMarksheet;
    }

}